<?php
/**
 * Created by Netivo for modules
 * User: manveru
 * Date: 2.10.2026
 * Time: 12:45
 *
 * @var $loop int
 * @var $variation_object WC_Product_Variation
 * @var $config array
 */
if ( ! defined( 'ABSPATH' ) ) {
	header( 'HTTP/1.0 403 Forbidden' );
	exit;
}

if ( ! empty( $config ) ) {
	foreach ( $config as $id => $stk ) {
		if ( ! empty( $stk['manage'] ) ) {
			$meta_key      = '_ex_stock_' . $id;
			$meta_key_sync = '_ex_sync_' . $id;
			$meta_key_rt   = '_ex_time_' . $id;
			woocommerce_wp_text_input(
				array(
					'id'                => 'variable' . $meta_key . $loop,
					'name'              => 'variable' . $meta_key . '[' . $loop . ']',
					'value'             => wc_stock_amount( $variation_object->get_meta( $meta_key ) ),
					'label'             => sprintf( __( 'Stan magazynowy %s', 'netivo' ), $stk['name'] ),
					'desc_tip'          => true,
					'description'       => sprintf( __( 'Opcja pozwala na kontrolę stanu magazynowego z magazynu %s', 'netivo' ), $stk['name'] ),
					'type'              => 'number',
					'custom_attributes' => array(
						'step' => 'any',
					),
					'data_type'         => 'stock',
					'wrapper_class'     => ( ! empty( $stk['realisation_time'] ) ) ? 'form-row form-row-first' : 'form-row form-row-full',
				)
			);

			if ( ! empty( $stk['realisation_time'] ) ) {
				woocommerce_wp_text_input(
					array(
						'id'            => 'variable' . $meta_key_rt . $loop,
						'name'          => 'variable' . $meta_key_rt . '[' . $loop . ']',
						'value'         => $variation_object->get_meta( $meta_key_rt ),
						'label'         => sprintf( __( 'Czas realizacji z magazynu %s (dni)', 'netivo' ), $stk['name'] ),
						'placeholder'   => wc_format_localized_decimal( 0 ),
						'desc_tip'      => true,
						'description'   => sprintf( __( 'Czas realizacji z magazynu %s w dniach', 'netivo' ), $stk['name'] ),
						'type'          => 'text',
						'data_type'     => 'decimal',
						'wrapper_class' => 'form-row form-row-last',
					)
				);
			}
			if ( ! empty( $stk['synchronize'] ) ) {
				woocommerce_wp_checkbox(
					array(
						'id'            => 'variable' . $meta_key_sync . $loop,
						'name'          => 'variable' . $meta_key_sync . '[' . $loop . ']',
						'value'         => $variation_object->get_meta( $meta_key_sync ),
						'cbvalue'       => 1,
						'label'         => sprintf( __( 'Synchronizuj stan magazynowy %s', 'netivo' ), $stk['name'] ),
						'wrapper_class' => 'form-row form-row-full',
					)
				);
			}
		}
	}
}

if ( \Netivo\Module\WooCommerce\Stocks\Module::is_realisation_time_enabled() ) {
	woocommerce_wp_text_input(
		array(
			'id'            => 'variable_realisation_time' . $loop,
			'name'          => 'variable_realisation_time[' . $loop . ']',
			'value'         => $variation_object->get_meta( '_realisation_time' ),
			'label'         => __( 'Czas realizacji (brak w magazynach)', 'netivo' ),
			'placeholder'   => wc_format_localized_decimal( 0 ),
			'desc_tip'      => true,
			'description'   => __( 'Czas realizacji przy braku w magazynach w dniach', 'netivo' ),
			'type'          => 'text',
			'data_type'     => 'decimal',
			'wrapper_class' => 'form-row form-row-full',
		)
	);
}
